services:
  timecapsule-api:
    container_name: timecapsule-api
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - SPRING_PROFILES_ACTIVE=production
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://timecapsule-database:3306/timecapsule?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "root"
    ports:
      - "8080:8080"
    networks:
      - timecapsule-network
    depends_on:
      - timecapsule-database

  timecapsule-database:
    container_name: timecapsule-database
    image: mysql/mysql-server:8.0
    environment:
      MYSQL_DATABASE: timecapsule
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    ports:
      - 3306:3306
    volumes:
      - ./.db/data:/var/lib/mysql
    networks:
      - timecapsule-network

networks:
  timecapsule-network:
    driver: bridge
