---
spring:
  config:
    activate:
      on-profile: test, local
  datasource:
    username: aaaa
    password: bbbb
    jpa-hibernate-ddl-auto: create
    url: jdbc:h2:mem:default;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    maximum-pool-size: 2
    connection-timeout: 3000
    driver-class-name: org.h2.Driver

    jpa:
      hibernate:
        ddl-auto: create
      show-sql: true
      properties:
        hiberante.format_sql: true

  logging:
    level:
      org.hibernate.SQL: DEBUG

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    username: timecapsule
    password: timecapsule
    jpa-hibernate-ddl-auto: validate
    url: jdbc:mysql://timecapsule-dev-database:3305/timecapsule?serverTimezone=Asia/Seoul
    maximum-pool-size: 10
    connection-timeout: 3000
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hiberante.format_sql: true

logging:
  level:
    org.hibernate.SQL: DEBUG

---
spring:
  config:
    activate:
      on-profile: production
  datasource:
    username: timecapsule
    password: timecapsule
    jpa-hibernate-ddl-auto: validate
    url: jdbc:mysql://timecapsule-database:3306/timecapsule?useSSL=false&allowPublicKeyRetrieval=true
    maximum-pool-size: 10
    connection-timeout: 3000
    driver-class-name: com.mysql.cj.jdbc.Driver
