name: Timecapsule-CI

on:
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew clean build
    - name: Test with Gradle
      run: ./gradlew --info test
    - name: Publish Unit Test Results # 테스트 후 Result를 보기위해 Publish Unit Test Results step 추가
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: ${{ always() }}  # 테스트가 실패하여도 Report를 보기 위해 `always`로 설정
      with:
        files: build/test-results/**/*.xml
